"""Add last_external_sync to stores

Revision ID: 26a6cba2417c
Revises: 417f5e59da4c
Create Date: 2026-05-07 21:36:46.438356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26a6cba2417c'
down_revision = '417f5e59da4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comparison_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('comparison_logs_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comparison_logs_winner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'items', ['winner_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index('ix_contact_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_contact_email', ['email'], unique=False)
        batch_op.create_index('ix_contact_is_read', ['is_read'], unique=False)

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('item_images_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_recommendations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_rec_type'))
        batch_op.create_index('ix_item_rec_lookup', ['item_id', 'rec_type'], unique=False)
        batch_op.create_unique_constraint('uq_item_rec', ['item_id', 'recommended_item_id'])

    with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
        batch_op.alter_column('subscribed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index('ix_price_alert_lookup', ['email', 'item_id', 'is_active'], unique=False)

    with op.batch_alter_table('quiz_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('quiz_logs_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_external_sync', sa.DateTime(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_view'), type_='unique')
        batch_op.create_index('ix_views_dedup', ['target_type', 'target_id', 'created_at'], unique=False)
        batch_op.create_index('uq_view_ip', ['ip_address', 'target_type', 'target_id'], unique=True, postgresql_where=sa.text('ip_address IS NOT NULL'))
        batch_op.create_index('uq_view_user', ['user_id', 'target_type', 'target_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_index('uq_view_user', postgresql_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index('uq_view_ip', postgresql_where=sa.text('ip_address IS NOT NULL'))
        batch_op.drop_index('ix_views_dedup')
        batch_op.create_unique_constraint(batch_op.f('unique_view'), ['user_id', 'ip_address', 'target_type', 'target_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('last_external_sync')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('quiz_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quiz_logs_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_price_alert_lookup')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('newsletter_subscribers', schema=None) as batch_op:
        batch_op.alter_column('subscribed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('item_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_item_rec', type_='unique')
        batch_op.drop_index('ix_item_rec_lookup')
        batch_op.create_index(batch_op.f('idx_rec_type'), ['rec_type'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('item_images_item_id_fkey'), 'items', ['item_id'], ['id'])

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_is_read')
        batch_op.drop_index('ix_contact_email')
        batch_op.drop_index('ix_contact_created_at')
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('comparison_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comparison_logs_winner_id_fkey'), 'items', ['winner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comparison_logs_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
