"""Add last_external_sync to stores

Revision ID: 26a6cba2417c
Revises: 417f5e59da4c
Create Date: 2026-05-07 21:36:46.438356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26a6cba2417c'
down_revision = '417f5e59da4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_external_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('last_external_sync')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
