"""add_admitad_feed_support

Revision ID: 417f5e59da4c
Revises: f2a94b7c1d05
Create Date: 2026-05-06 21:28:06.034933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '417f5e59da4c'
down_revision = 'f2a94b7c1d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=True),
    sa.Column('new_added', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('deactivated', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('item_store_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('imported_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ean_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_ean_code'), ['ean_code'], unique=False)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xml_feed_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feed_format', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_auto_sync', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('is_auto_sync')
        batch_op.drop_column('feed_format')
        batch_op.drop_column('xml_feed_url')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_ean_code'))
        batch_op.drop_column('ean_code')

    with op.batch_alter_table('item_store_links', schema=None) as batch_op:
        batch_op.drop_column('imported_at')
        batch_op.drop_column('source')

    op.drop_table('feed_sync_logs')
    # ### end Alembic commands ###

